apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/part-of: connectivity-link-tutorial
spec:
  observability:
    enable: true
