apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: echo-auth
  namespace: tutorial-app
  labels:
    app.kubernetes.io/part-of: connectivity-link-tutorial
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echo
  rules:
    authentication:
      keycloak-jwt:
        jwt:
          issuerUrl: https://sso.${CLUSTER_DOMAIN}/realms/connectivity-link-tutorial
