apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: echo-auth
  namespace: tutorial-app
  labels:
    app.kubernetes.io/part-of: connectivity-link-tutorial
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echo
  rules:
    authentication:
      keycloak-jwt:
        jwt:
          issuerUrl: https://keycloak.${CLUSTER_DOMAIN}/realms/connectivity-link-tutorial
    authorization:
      ip-denylist:
        opa:
          rego: "allow = false"
        when:
          - predicate: >-
              request.headers['x-forwarded-for'].startsWith('$CLIENT_IP')
    response:
      unauthorized:
        headers:
          "content-type":
            value: application/json
        body:
          value: '{"error": "Forbidden", "message": "Your IP has been blocked"}'
