apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: tempo-bucket
  namespace: tempo
  labels:
    app.kubernetes.io/part-of: connectivity-link-tutorial
spec:
  generateBucketName: tempo-bucket
  storageClassName: openshift-storage.noobaa.io
