quarkus.http.port=${HTTP_PORT:8080}
quarkus.package.jar.type=uber-jar
quarkus.native.enabled=false

# The context path under which all services will be available
quarkus.cxf.path = /soap

# Publish "HelloService" under the context path /${quarkus.cxf.path}/hello
quarkus.cxf.endpoint."/hello".implementor = com.redhat.nlembers.soap.HelloServiceImpl
quarkus.cxf.endpoint."/hello".logging.enabled = pretty