apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openshift-default
  labels:
    app.kubernetes.io/part-of: connectivity-link-tutorial
spec:
  controllerName: openshift.io/gateway-controller/v1
